pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [jakubjanecek]
      label:
        add: [dependency-update]
  - name: merge Scala Steward's PRs
    conditions:
      - base=master
      - author=scala-steward
      - status-success=PR Build
    actions:
      merge:
        method: merge
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
      - status-success=PR Build
    actions:
      merge:
        method: squash
      delete_head_branch:
        force: true
