// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.1.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      )
  }
}
// LIBRARY_DEPENDENCIES_HASH ba84f20fadaccb0040e68a530ed6863bd523148b
