// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.1.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "com.github.ghik" % "silencer-lib_2.13.0" % "1.4.3",
      "org.typelevel" % "cats-core_2.13" % "2.0.0",
      "org.typelevel" % "cats-effect_2.13" % "2.0.0",
      "org.typelevel" % "cats-kernel_2.13" % "2.0.0",
      "org.typelevel" % "cats-macros_2.13" % "2.0.0"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH 3c115232d5575d261ed52ade3d2e64044c9447e4
