// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.1.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "com.chuusai" % "shapeless_2.13" % "2.3.3",
      "com.github.ghik" % "silencer-lib_2.13.0" % "1.4.3",
      "com.github.pureconfig" % "pureconfig-core_2.13" % "0.12.0",
      "com.github.pureconfig" % "pureconfig-generic_2.13" % "0.12.0",
      "com.github.pureconfig" % "pureconfig-macros_2.13" % "0.12.0",
      "com.github.pureconfig" % "pureconfig_2.13" % "0.12.0",
      "com.typesafe" % "config" % "1.3.4",
      "org.typelevel" % "cats-core_2.13" % "2.0.0",
      "org.typelevel" % "cats-effect_2.13" % "2.0.0",
      "org.typelevel" % "cats-kernel_2.13" % "2.0.0",
      "org.typelevel" % "cats-macros_2.13" % "2.0.0"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH cc2062c5868351c2b8bc80a5d96634a63585dd78
